
set identity_insert [Review] on
insert into Review (Id, Title, Content, ImageLocation, CreateDateTime, Category, Stars, UserProfileId) values (1, 'Beneath the Planet of the Apes', 'The first sequel to the enormously successful Planet of the Apes is also the best. Less subtle and profound than its predecessor, its still an exciting and colourful action adventure. This time out, astronaut James Franciscus and chimpanzee scientist Kim Hunter search for Charlton Heston (star of the first film) in the nuclear-devastated future, evading militaristic apes only to stumble upon an underground community of mutant, telepathic humans. It ends somewhat hammily in the buried ruins of Grand Central Station, but the total destruction of the world didnt stop three more progressively silly sequels. In fact, the finale manages a startling impact considering the films tendency to wallow in the camper aspects of its taut material.', 'http://lorempixel.com/920/360/', '2019-12-04', 'Action', 3, 1);
insert into Review (Id, Title, Content, ImageLocation, CreateDateTime, Category, Stars, UserProfileId) values (25, 'Boogie Nights', 'Boogie Nights, also included in the New York Film Festival, is another fireball in a time capsule. A tumultuous two and a half-hour evocation of sex in the ’70s, this chunk of movie dynamite is detonated by Mark Wahlberg, the rapper formerly known as Marky Mark, who grabs a breakout role and runs with it. What sounds like a tacky peek into the inner workings of the porn industry in the late ’70s, when President Carter admitted to having lust in his heart, is like The Ice Storm, a film about family. Just don’t think Disney, since the teen busboy hero, Eddie Adams (Wahlberg), who is estranged from his parents, rises to X-rated fame on the size of his dick (Wahlberg wears a prosthetic device) and his apt new name, Dirk Diggler.', 'http://lorempixel.com/920/360/', '2019-12-04', 'Mystory', 1, 2);
insert into Review (Id, Title, Content, ImageLocation, CreateDateTime, Category, Stars, UserProfileId) values (2, '2001 a space odyssey', 'The genius is not in how much Stanley Kubrick does in "2001: A Space Odyssey," but in how little. This is the work of an artist so sublimely confident that he doesnt include a single shot simply to keep our attention. He reduces each scene to its essence, and leaves it on screen long enough for us to contemplate it, to inhabit it in our imaginations. Alone among science-fiction movies, “2001" is not concerned with thrilling us, but with inspiring our awe.', 'http://lorempixel.com/920/360/', '2019-12-04', 'Mystory', 1, 6);
insert into Review (Id, Title, Content, ImageLocation, CreateDateTime, Category, Stars, UserProfileId) values (13, 'Reservoir Dogs', 'Six criminals with pseudonyms, and each strangers to one another, are hired to carry out a robbery. The heist is ambushed by police and the gang are forced to shoot their way out. At their warehouse rendezvous, the survivors, realising that they were set up, try to find the traitor in their midst.', 'http://lorempixel.com/920/360/', '2019-12-04', 'Mystory', 1, 7);
insert into Review (Id, Title, Content, ImageLocation, CreateDateTime, Category, Stars, UserProfileId) values (18, 'Pulp Fiction', 'One of the early scenes in "Pulp Fiction" features two hit-men discussing what a Big Mac is called in other countries. Their dialogue is witty and entertaining, and its also disarming, because it makes these two thugs seem all too normal. If you didnt know better, you might assume these were regular guys having chit-chat on their way to work. Other than the comic payoff at the end of the scene, in which they use parts of this conversation to taunt their victims, their talk has no relevance to anything in the film, or to anything else, for that matter. Yet without such scenes, "Pulp Fiction" wouldnt be "Pulp Fiction." I get the sense that Tarantino put into the film whatever struck his fancy, and somehow the final product is not only coherent but wonderfully textured.', 'http://lorempixel.com/920/360/', '2019-12-04', 'Mystory', 1, 4);
insert into Review (Id, Title, Content, ImageLocation, CreateDateTime, Category, Stars, UserProfileId) values (22, 'Eyes Wide Shut', 'Stanley Kubricks "Eyes Wide Shut'' is like an erotic daydream about chances missed and opportunities avoided. For its hero, who spends two nights wandering in the sexual underworld, its all foreplay. He never actually has sex, but he dances close, and holds his hand in the flame. Why does he do this? The easy answer is that his wife has made him jealous. Another possibility is that the story she tells inflames his rather torpid imagination.', 'http://lorempixel.com/920/360/', '2019-12-04', 'Mystory', 1, 8);
insert into Review (Id, Title, Content, ImageLocation, CreateDateTime, Category, Stars, UserProfileId) values (4, 'End of Evangelion ', 'The beauty of End of Evangelion is that it can mean many things to many people, that it answers copious narrative questions while still leaving many open doors. End of Evangelion offers its audience the same choice it offers its heroes, and ultimately, that choice is a reflection of its clear faith in our fundamental human nature. “I believe in you,” says Evangelion, as it opens the door to a frightening, exhilarating adult world. “You should believe in you, too.”', 'http://lorempixel.com/920/360/', '2019-12-04', 'Mystory', 1, 1);
insert into Review (Id, Title, Content, ImageLocation, CreateDateTime, Category, Stars, UserProfileId) values (7, 'Herditary', 'Hereditary is not for the faint of heart. Honestly, we really mean it. But not in the sense that it might loudly jump-scare you into cardiac arrest. Ari Aster’s feature debut has its thorax-tightening shock moments, but they are rare (and all the more effective for it). Primarily, it takes the crawling-dread approach to horror, often serving up its most chilling shriek-treats before you even notice they’re right there in front of you.', 'http://lorempixel.com/920/360/', '2019-12-04', 'Mystory', 1, 2);
insert into Review (Id, Title, Content, ImageLocation, CreateDateTime, Category, Stars, UserProfileId) values (14, 'Midsommar', 'Whatever you think of the end result, there’s always something thrilling about watching a young director who’s earned a long line of Hollywood credit decide to spend every last cent of it on a single film. And writer-director Ari Aster has certainly done that with his “Hereditary” follow-up, “Midsommar.” Following a group of American grad students on a trip to a mysterious midnight sun festival in Sweden, Aster gives us a slow-burning, boldly-made meditation on grief and the disintegration of a relationship in the loose frame of a folk horror film, yet it struggles to break much new ground beneath its carnival of brightly lit grotesqueries.', 'http://lorempixel.com/920/360/', '2019-12-04', 'Mystory', 1, 4);
insert into Review (Id, Title, Content, ImageLocation, CreateDateTime, Category, Stars, UserProfileId) values (24, 'Hard 8', 'Hard Eight opens with a fascinating, twenty-minute prologue. A dapper, elderly gentleman named Sydney (Philip Baker Hall), approaches a disheveled, younger man, John (John C. Reilly), outside a roadside diner. Sydney invites John to join him for a cup of coffee and a cigarette. Inside, they talk. Johns on his way back from Vegas, where he lost all his money trying to win enough to bury his mother. Sydney thinks his intentions are admirable, and offers him an opportunity: come back to Vegas and learn how to get a free room and maybe even win a little extra cash. Sydneys scam is deceptively simple and undeniably effective, and Anderson presents it with flair and an undercurrent of wry humor.', 'http://lorempixel.com/920/360/', '2019-12-04', 'Mystory', 1, 6);
insert into Review (Id, Title, Content, ImageLocation, CreateDateTime, Category, Stars, UserProfileId) values (3, 'Ricky Bobby', 'Three cheers for Ricky Bobby -- the man, the myth, the name. The title of this pitch-perfect parody of an auto-racing biopic is "Talladega Nights: The Ballad of Ricky Bobby," but the racing heros name is so great (and so much fun to say) that people are already just calling it "Ricky Bobby." The first time I heard the title characters nom de tube in "Anchorman: The Legend of Ron Burgundy," the previous collaboration between Will Farrell and Adam McKay, I laughed out loud. A 1970s local newscaster? What better name than Ron Burgundy? And now, a NASCAR driver? Ricky Bobby, of course!', 'http://lorempixel.com/920/360/', '2019-12-04', 'Mystory', 1, 7);
insert into Review (Id, Title, Content, ImageLocation, CreateDateTime, Category, Stars, UserProfileId) values (19, 'This is the End', 'Is this movie silly? Yes. Is it packed with toilet humor? Yes. Do you see the erect (and later, flaccid) penis of a monster? Yes. Is there an important take-home message you get from watching it? Absolutely not. So why am I giving it 10 stars? Because it made me laugh uncontrollably. Maybe Im different but even cheap laughs are good laughs.', 'http://lorempixel.com/920/360/', '2019-12-04', 'Mystory', 1, 8);
insert into Review (Id, Title, Content, ImageLocation, CreateDateTime, Category, Stars, UserProfileId) values (21, 'Pineapple Express', '"Pineapple Express" has all the elements youd expect from the genre: male bonding, immature sexual desires, verbal scatology, formidable drug abuse, fight scenes, gunfire, explosions. Yawn? Not this time. Its a quality movie even if the material is unworthy of the treatment. As a result, yes, its a druggie comedy that made me laugh.', 'http://lorempixel.com/920/360/', '2019-12-04', 'Mystory', 1, 1);
insert into Review (Id, Title, Content, ImageLocation, CreateDateTime, Category, Stars, UserProfileId) values (8, 'Napoleon Dynamite', 'We can laugh at comedies like this for two reasons: Because we feel superior to the characters, or because we pity or like them. I do not much like laughing down at people, which is why the comedies of Adam Sandler make me squirmy (most people, I know, laugh because they like him). In the case of Napoleon Dynamite (Jon Heder), I certainly dont like him, but then the movie makes no attempt to make him likable. Truth is, it doesnt even try to be a comedy. It tells his story and we are supposed to laugh because we find humor the movie pretends it doesnt know about.', 'http://lorempixel.com/920/360/', '2019-12-04', 'Mystory', 1, 2);
insert into Review (Id, Title, Content, ImageLocation, CreateDateTime, Category, Stars, UserProfileId) values (17, 'Monty Python and the Holy Grail', 'ust after Robert Bresson’s Lancelot of the Lake and before John Boorman’s Excalibur there was Monty Python and the Holy Grail (1975), the Pythons’ classic Arthurian hallucination. Now rereleased in cinemas on its 40th anniversary, the film was their bridgehead into international stardom. Watched again now on the big screen, it is eerie to see how, without the gags, much of its cinematography and imagery could actually be taken entirely seriously. (“Ingmar Bergman’s gonna be jealous of this one!” co-director Terry Gilliam told a BBC Film Night location reporter at the time.)', 'http://lorempixel.com/920/360/', '2019-12-04', 'Mystory', 1, 4);
insert into Review (Id, Title, Content, ImageLocation, CreateDateTime, Category, Stars, UserProfileId) values (23, 'Schindlers List', 'Here is a man who saw his chance at the beginning of World War II and moved to Nazi-occupied Poland to open a factory and employ Jews at starvation wages. His goal was to become a millionaire. By the end of the war, he had risked his life and spent his fortune to save those Jews and had defrauded the Nazis for months with a munitions factory that never produced a single usable shell.', 'http://lorempixel.com/920/360/', '2019-12-04', 'Mystory', 1, 6);
insert into Review (Id, Title, Content, ImageLocation, CreateDateTime, Category, Stars, UserProfileId) values (9, 'Clockwork Orange', 'Completely brilliant. This film is amazing in its characterization, its pacing, its character development and its visuals. The book is superb, but Stanley is a genius who has a midas touch.', 'http://lorempixel.com/920/360/', '2019-12-04', 'Mystory', 1, 7);
insert into Review (Id, Title, Content, ImageLocation, CreateDateTime, Category, Stars, UserProfileId) values (20, 'Goodfellas', 'For two days after I saw Martin Scorseses new film, "GoodFellas," the mood of the characters lingered within me, refusing to leave. It was a mood of guilt and regret, of quick stupid decisions leading to wasted lifetimes, of loyalty turned into betrayal. Yet at the same time there was an element of furtive nostalgia, for bad times that shouldnt be missed, but were.Most films, even great ones, evaporate like mist once youve returned to the real world; they leave memories behind, but their reality fades fairly quickly. Not this film, which shows Americas finest filmmaker at the peak of his form. No finer film has ever been made about organized crime - not even "The Godfather," although the two works are not really comparable.', 'http://lorempixel.com/920/360/', '2019-12-04', 'Mystory', 1, 8);
insert into Review (Id, Title, Content, ImageLocation, CreateDateTime, Category, Stars, UserProfileId) values (5, 'The Irishman', 'I dot know where to start on this one other than thanking Netflix for being the only distributor to fund this movie so we could see Big screen legends take their last big swing. The set and screen is smaller than I liked it to be, it being released on a streaming site but its better than never seeing it.Its not a flawless movie and I wouldnt necessarily call it a masterpiece or something new and innovative. But for an old genre gangsta flick its easily one of the best ones out there.', 'http://lorempixel.com/920/360/', '2019-12-04', 'Mystory', 1, 1);
insert into Review (Id, Title, Content, ImageLocation, CreateDateTime, Category, Stars, UserProfileId) values (10, 'Birdman', 'The first thing you applaud about Birdman is Keaton’s audacity in accepting the role of neurotic Tinseltown veteran Riggan Thomson – and Iñárritu’s chutzpah in offering it to him. The payoff is a considerable comeback for both men. The actor will be unavoidable during the awards season, while the Mexican virtuoso director of Amores Perros fame stages a triumphant return to form after his lugubriously self-important woes-of-the-world drama Biutiful.', 'http://lorempixel.com/920/360/', '2019-12-04', 'Mystory', 1, 2);
insert into Review (Id, Title, Content, ImageLocation, CreateDateTime, Category, Stars, UserProfileId) values (6, 'The Shinning', 'My favorite film of Kubricks. You feel like youre becoming as mad as Johnny while watching, building up cabin fever and fear in a mixture of nauseous scenes.', 'http://lorempixel.com/920/360/', '2019-12-04', 'Mystory', 1, 4);
insert into Review (Id, Title, Content, ImageLocation, CreateDateTime, Category, Stars, UserProfileId) values (11, 'Fargo', 'The Coen brothers have does a terrific job on this movie. Its a well written, original story with an original setting and it doesnt try to be anything it isnt. Just a few characters, a simple plot and small scale. They stay away of clichés and dont even remotely try to mix in anything of that regular Hollywood crap. They manage to capture the mood, the people and the action pretty good. The characters are great, theyre reasonable and believable. They manage to keep it serious, but not too serious and put inn a joke here and there.', 'http://lorempixel.com/920/360/', '2019-12-04', 'Mystory', 1, 6);
insert into Review (Id, Title, Content, ImageLocation, CreateDateTime, Category, Stars, UserProfileId) values (15, 'The Big Lebowski', 'The Big Lebowski is the type of movie that is so funny, and so clever, you want nothing more but to meet the Coen brothers, congratulate them personally for their unique talent, and get inside their heads and find out what makes these two geniuses "tick". The main characters are Jeff Bridges (who plays such broad roles like The Muse, The Contender, and Sea Biscuit), John Goodman (who should have won an oscar for best supporting actor for his character, Walter Sobchak)Juliane Moore (Maude Lebowski)and Steve Buscemi (who is unique in every Coen Brother movie).', 'http://lorempixel.com/920/360/', '2019-12-04', 'Mystory', 1, 7);
insert into Review (Id, Title, Content, ImageLocation, CreateDateTime, Category, Stars, UserProfileId) values (12, 'Momento', 'Christopher Nolans "Memento" is truly a rare and exceptional achievement in modern filmmaking in that it manages to be new, fresh, hip, and exciting without ever tiring its audience out - unless youre walking into this film without the desire to participate and actively analyze the mysterious details.', 'http://lorempixel.com/920/360/', '2019-12-04', 'Mystory', 1, 8);
insert into Review (Id, Title, Content, ImageLocation, CreateDateTime, Category, Stars, UserProfileId) values (16, 'Joker', 'Truly a masterpiece, The Best Hollywood film of 2019, one of the Best films of the decade... And truly the Best film to bring a comic book so chillingly and realistically to real ife. Remarkable Direction, Cinematography, Music and the Acting. Some people are surprised to find it DISTURBING and VIOLENT, but its a necessity and message.', 'http://lorempixel.com/920/360/', '2019-12-04', 'Mystory', 1, 1);
set identity_insert [Review] off

set identity_insert [Comment] on
insert into Comment (Id, ReviewId, UserProfileId, Content, CreateDateTime) values (1, 1, 1, 'My Comment1', '2020-05-19');
insert into Comment (Id, ReviewId, UserProfileId, Content, CreateDateTime) values (2, 2, 2, 'My Comment2', '2020-05-11');
set identity_insert [Comment] off

set identity_insert [FavoritePost] on
insert into FavoritePost (Id, Title, CreateDateTime, UserProfileId) values (1, 'Top10', '2019-12-04', 1);
insert into FavoritePost (Id, Title, CreateDateTime, UserProfileId) values (2, 'Top5', '2019-12-04', 2);
set identity_insert [FavoritePost] off

set identity_insert [FavoriteMovies] on
insert into FavoriteMovies (Id, FavoritePostId, ReviewId, Why) values (1, 1, 1, 'This is my fav Movie1');
insert into FavoriteMovies (Id, FavoritePostId, ReviewId, Why) values (2, 2, 2, 'This is my fav Movie2');
set identity_insert [FavoriteMovies] off
